/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_JSContext */

#ifndef _Included_com_company_JSContext
#define _Included_com_company_JSContext
#ifdef __cplusplus
extern "C" {
    
#endif
/*
 * Class:     com_company_JSContext
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_company_JSContext_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_company_JSContext
 * Method:    executeScript
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_company_JSContext_executeScript
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_company_JSContext
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_company_JSContext_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
