/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_company_V8 */

#ifndef _Included_com_company_V8
#define _Included_com_company_V8
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_company_V8
 * Method:    initialize0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_company_V8_initialize0
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
